FROM kartoza/postgis:latest
# Обновляем пакетный менеджер
#RUN apt-get update -y && apt-get upgrade -y
#RUN apt-get install postgresql-13 -y
#RUN apt-get install postgresql-13-postgis-3 -y
#RUN apt-get install postgis -y